### ISSUE TITLE
Upgrade TestNG to 7.5

### ISSUE THREAD

**Issue by baubakg** [adobe/phased-testing#39]
We need to upgrade TestNG to 7.5 to allow nested class tests

**Comment by baubakg** [comment]
Issue with 
```
DEBUG | 2022-01-24 18:19:10 | [main] phased.PhasedTestListener (PhasedTestListener.java:436) - [Phased Testing] Keeping com.adobe.campaign.tests.integro.phased.data.befaft.PhasedSeries_M_ShuffledClass_noproviders.step1(phased-shuffledGroup_1_2) because when all results are skipped we keep only the first one..

java.lang.IllegalArgumentException: No parameters found. The given test result for test com.adobe.campaign.tests.integro.phased.data.befaft.PhasedSeries_M_ShuffledClass_noproviders.step2 does not seem to have been part of a Phased Test

	at com.adobe.campaign.tests.integro.phased.PhasedTestManager.fetchPhasedStepName(PhasedTestManager.java:1140)
	at com.adobe.campaign.tests.integro.phased.PhasedTestListener.appendShuffleGroupToName(PhasedTestListener.java:250)
	at com.adobe.campaign.tests.integro.phased.PhasedTestListener.standardPostTestActions(PhasedTestListener.java:283)
	at com.adobe.campaign.tests.integro.phased.PhasedTestListener.onTestFailure(PhasedTestListener.java:266)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:99)
	at org.testng.internal.invokers.TestInvoker.runTestResultListener(TestInvoker.java:276)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.adobe.campaign.tests.integro.phased.TestPhased_BEFORE_AFTER.testBEFORE_PHASE_testSimpleSuiteTests_failBeforePhase(TestPhased_BEFORE_AFTER.java:225)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
```

**Comment by baubakg** [comment]
Seems in this use case in:

7.4.0
* As opposed to the normal cases, parameters not present in onTestStart, however they appear in all onTestX.
** This does not change in the case of executing with other tests.

**Comment by baubakg** [comment]
Problem related to soluion in #41
